/**
 * Ergonomic re-exports of the (auto-generated) OpenAPI types.
 *
 * `src/types/openapi.d.ts` is regenerated by `npm run sync` and exposes
 * everything via the heavyweight `paths`/`components` interfaces. The
 * aliases here narrow them down to the shapes consumers actually
 * import — request bodies, response bodies, common enums.
 *
 * If you need a type that isn't aliased yet, you can always reach the
 * raw OpenAPI types via `import type { components, paths } from
 * '@apiframe-ai/sdk'`.
 */

import type { components, paths } from './openapi.js';

// ---------------------------------------------------------------------------
// Request bodies — what the SDK methods accept
// ---------------------------------------------------------------------------

export type ImagesGenerateInput = components['schemas']['GenerateImageRequest'];
export type ImagesUpscaleInput = components['schemas']['ImageUpscaleRequest'];
export type ImagesEditInput = components['schemas']['ImageEditRequest'];
export type ImagesRemoveBackgroundInput = components['schemas']['ImageBackgroundRemoveRequest'];

export type VideosGenerateInput = components['schemas']['GenerateVideoRequest'];
export type VideosUpscaleInput = components['schemas']['VideoUpscaleRequest'];
export type VideosEditInput = components['schemas']['VideoEditRequest'];

export type MusicGenerateInput = components['schemas']['GenerateMusicRequest'];

export type CreateAssetInput = components['schemas']['CreateAssetRequest'];

// ---------------------------------------------------------------------------
// Responses — what the SDK methods return
// ---------------------------------------------------------------------------

export type Job = components['schemas']['Job'];
export type JobAccepted = components['schemas']['JobAccepted'];
export type JobList = components['schemas']['JobList'];

export type MeResponse = components['schemas']['Me'];

export type ModelCatalog = components['schemas']['ModelCatalog'];
export type ModelCatalogEntry = components['schemas']['ModelCatalogEntry'];

export type Upload = components['schemas']['Upload'];

export type Lora = components['schemas']['Lora'];
export type LoraCreated = components['schemas']['LoraCreated'];
export type LoraList = components['schemas']['LoraList'];

export type AssetCreated = components['schemas']['AssetCreated'];

// ---------------------------------------------------------------------------
// Modality discriminators (handy for narrowing union types)
// ---------------------------------------------------------------------------

export type ImageGenerationModel = ImagesGenerateInput['model'];
export type VideoGenerationModel = VideosGenerateInput['model'];
export type MusicGenerationModel = MusicGenerateInput['model'];

export type ImageEditModel = ImagesEditInput['model'];
export type ImageUpscaleModel = ImagesUpscaleInput['model'];
export type ImageBackgroundRemoveModel = ImagesRemoveBackgroundInput['model'];
export type VideoEditModel = VideosEditInput['model'];
export type VideoUpscaleModel = VideosUpscaleInput['model'];

// ---------------------------------------------------------------------------
// Job query / list params (derived from path-level operation types)
// ---------------------------------------------------------------------------

/** Query parameters accepted by `GET /v2/jobs`. */
export type JobsListQuery = NonNullable<paths['/v2/jobs']['get']['parameters']['query']>;

/** Query parameters accepted by `GET /v2/loras`. */
export type LorasListQuery = NonNullable<paths['/v2/loras']['get']['parameters']['query']>;

/** Query parameters accepted by `GET /v2/models`. */
export type ModelsListQuery = NonNullable<paths['/v2/models']['get']['parameters']['query']>;

// ---------------------------------------------------------------------------
// Re-export the raw OpenAPI types for power users who want everything.
// ---------------------------------------------------------------------------

export type { components, paths };
